### ISSUE TITLE
About the graphq_trans

### ISSUE THREAD

**Issue by leezythu** [Flitternie/GraphQ_IR#2]
It a great work! Do you prepare to release the graphq_trans tool recently?

**Comment by Flitternie** [comment]
Thanks for your interest! Currently, there is a demo website for graphq_trans: https://graphqtrans.xlore.cn/ 
We are still finalizing the code and plan to release them as a python package. You may expect a release by the end of Oct.

**Comment by Flitternie** [comment]
Our graphq_trans package has been released! @leezythu 
Please refer to its repository for details: [https://github.com/Flitternie/GraphQ_Trans](https://github.com/Flitternie/GraphQ_Trans)

**Comment by leezythu** [comment]
Thanks a lot!
