### ISSUE TITLE
KoPL Conversion failure

### ISSUE THREAD

**Issue by leezythu** [Flitternie/GraphQ_IR#4]
Hi, I found that some programs cannot be converted into graphq. For example, when I run:
`from graphq_trans.kopl.translator import Translator
translator = Translator()
a = [{
                "function": "Find",
                "dependencies": [],
                "inputs": [
                    "My Neighbor Totoro"
                ]
            },
            {
                "function": "Find",
                "dependencies": [],
                "inputs": [
                    "German"
                ]
            },
            {
                "function": "Relate",
                "dependencies": [
                    1
                ],
                "inputs": [
                    "original language of film or TV show",
                    "backward"
                ]
            },
            {
                "function": "Find",
                "dependencies": [],
                "inputs": [
                    "Hannah Arendt"
                ]
            },
            {
                "function": "And",
                "dependencies": [
                    2,
                    3
                ],
                "inputs": []
            },
            {
                "function": "SelectBetween",
                "dependencies": [
                    0,
                    4
                ],
                "inputs": [
                    "duration",
                    "greater"
                ]
            }
        ]
a = translator.to_ir(a)`
I got a warning "<stdin> 1:130 no viable alternative at input 'Find(My Neighbor Totoro)Find(German)Relate(original language of film or TV show<c>backward)Find(Hannah Arendt)And()SelectBetween'", and the conversion failed.
Is it normal or how can I solve it?

**Comment by Flitternie** [comment]
In the updated version of KoPL, operators `SelectBetween(KEY, OP)` and `SelectAmong(KEY, OP)` are merged into a more generic operator of `Select(KEY, OP, TOPK, START)` (as in line 136 of our defined [KoPL's grammar](https://github.com/Flitternie/GraphQ_Trans/blob/master/kopl/Kopl.g4)).  

I have contacted the authors of KQA Pro regarding this issue. An updated dataset will be uploaded to their website soon.

**Comment by Flitternie** [comment]
For your information, the updated KQA Pro dataset is now available at [https://worksheets.codalab.org/rest/bundles/0xf3765406cb7a4f8092332c844c7dc3e6/contents/blob/](https://worksheets.codalab.org/rest/bundles/0xf3765406cb7a4f8092332c844c7dc3e6/contents/blob/)

**Comment by Flitternie** [comment]
@leezythu This issue will now close. You may reopen this issue if you have further questions about the updated dataset.
