### ISSUE TITLE
Question about the evaluation of OVERNIGHT

### ISSUE THREAD

**Issue by leezythu** [Flitternie/GraphQ_IR#5]
Hi, sorry to disturb you again. I have a question about the test accuracies on OVERNIGHT in the paper. After reading the code, I suppose the results of `GraphQ IR` correspond to a single trained model. But for `GraphQ IR*`, you select one best-performed model for each of the eight domains. So the results of `GraphQ IR*` actually correspond to eight trained models rather than a single one. Is it right? I would appreciate it if you can explain it to me.
![截屏2022-11-27 上午11 22 35](https://user-images.githubusercontent.com/41156182/204117765-45ac1b3b-2ff7-4746-baf8-7e1afbec59ca.png)

**Comment by Flitternie** [comment]
It should be the opposite. `GraphQ IR*` is a single model trained (fine-tuned) over the integration of 8 domains' data (as specified in the paper).  For `GraphQ IR`, we report the best-performed models for each of the eight domains. 

Please see `data/overnight/config.py` for our implementation details. When preprocessing data, you may pass `args.domain = 'all'` for training `GraphQ IR*`,  or pass the respective domain name for obtaining the domain-specific training results for `GraphQ IR`.

**Comment by Flitternie** [comment]
That means, for `GraphQ IR`, we trained and tested 8 separate models on their respective domain data

**Comment by leezythu** [comment]
Thanks for your explanation!
