### ISSUE TITLE
Question about Overnight

### ISSUE THREAD

**Issue by mug2mag** [Flitternie/GraphQ_IR#8]
@Flitternie 
hi,
From the link you offered for the Overnight dataset, there are only questions and logical forms included, but no corresponding answers are provided, right? How to get the answers? I find that we can execute the logical forms in the dataset to get the answers. Are there other methods to get the answers? Or if some other papers released the answers?
Looking forward to your reply. Very appreciate.

**Comment by Flitternie** [comment]
Yes, you need to execute the logical forms to get the answers. You may follow the instructions [here](https://github.com/rhythmcao/semantic-parsing-dual) or run `./pull_dependency_overnight.sh` to set up the executor. 

So far I haven't seen any papers or repositories that released the answers. But as soon as you set up the executors correctly, the logical form execution process would be really fast (less than 10 mins for the whole dataset I think).

**Comment by mug2mag** [comment]
Thanks very much for your reply. Yes, you are right, `./pull_dependency_overnight.sh` works.  I also have not found other works to release the answers.
