### ISSUE TITLE
Is any ways for convert s-expression to sparql or cypher ?

### ISSUE THREAD

**Issue by feng-1985** [Flitternie/GraphQ_IR#9]

**Comment by Flitternie** [comment]
So far our work does not support the conversion for s-expression. You may refer to some other works that implemented similar functionalities (like GrailQA: https://github.com/dki-lab/GrailQA/blob/main/utils/logic_form_util.py).

**Comment by Flitternie** [comment]
@feng-1985 This issue will now close. You may reopen this issue if you have further questions.
